package main.java;

public class Groups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.name
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.parent_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long parent_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.name
     *
     * @return the value of groups.name
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.name
     *
     * @param name the value for groups.name
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.parent_id
     *
     * @return the value of groups.parent_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.parent_id
     *
     * @param parent_id the value for groups.parent_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setParent_id(Long parent_id) {
        this.parent_id = parent_id;
    }
}