
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int countByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int deleteByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    List<Permissions> selectByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    Permissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByExampleSelective(@Param("record") Permissions record, @Param("example") PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByExample(@Param("record") Permissions record, @Param("example") PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByPrimaryKey(Permissions record);
}