package main.java;

public class Permissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.name
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.id
     *
     * @return the value of permissions.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.id
     *
     * @param id the value for permissions.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.name
     *
     * @return the value of permissions.name
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.name
     *
     * @param name the value for permissions.name
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}