package main.java;

public class RolePermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.permission_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long permission_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long role_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.id
     *
     * @return the value of role_permissions.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.id
     *
     * @param id the value for role_permissions.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.permission_id
     *
     * @return the value of role_permissions.permission_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getPermission_id() {
        return permission_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.permission_id
     *
     * @param permission_id the value for role_permissions.permission_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setPermission_id(Long permission_id) {
        this.permission_id = permission_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_id
     *
     * @return the value of role_permissions.role_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_id
     *
     * @param role_id the value for role_permissions.role_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setRole_id(Long role_id) {
        this.role_id = role_id;
    }
}