package main.java;

import java.util.List;
import main.java.Roles;
import main.java.RolesExample;
import org.apache.ibatis.annotations.Param;

public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int countByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int deleteByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int insert(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int insertSelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    List<Roles> selectByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    Roles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByExampleSelective(@Param("record") Roles record, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByExample(@Param("record") Roles record, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByPrimaryKeySelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByPrimaryKey(Roles record);
}