
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int insert(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int insertSelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    List<UserRoles> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    UserRoles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByExampleSelective(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByExample(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByPrimaryKeySelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    int updateByPrimaryKey(UserRoles record);
}