package main.java;

public class UserGroups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_groups.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_groups.user_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_groups.group_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long group_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_groups.id
     *
     * @return the value of user_groups.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_groups.id
     *
     * @param id the value for user_groups.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_groups.user_id
     *
     * @return the value of user_groups.user_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_groups.user_id
     *
     * @param user_id the value for user_groups.user_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_groups.group_id
     *
     * @return the value of user_groups.group_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_groups.group_id
     *
     * @param group_id the value for user_groups.group_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setGroup_id(Long group_id) {
        this.group_id = group_id;
    }
}