
public class UserRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    private Long user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.id
     *
     * @return the value of user_roles.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.id
     *
     * @param id the value for user_roles.id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_id
     *
     * @return the value of user_roles.role_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_id
     *
     * @param role_id the value for user_roles.role_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setRole_id(Long role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_id
     *
     * @return the value of user_roles.user_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_id
     *
     * @param user_id the value for user_roles.user_id
     *
     * @mbggenerated Wed Jul 22 01:57:37 MSK 2015
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }
}